import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { isEnoent } from "../utils/errors.js";
import { getBundledRalphDir } from "./metadata.js";

const TEMPLATE_PLACEHOLDERS: Record<string, string> = {
  "PROMPT.md": "[YOUR PROJECT NAME]",
  "AGENT.md": "pip install -r requirements.txt",
};

const RALPHRC_TEMPLATE_NAME = "RALPHRC";
const CLAUDE_ALLOWED_TOOLS_TEMPLATE_LINE =
  'ALLOWED_TOOLS="Write,Read,Edit,MultiEdit,Glob,Grep,Task,TodoWrite,WebFetch,WebSearch,EnterPlanMode,ExitPlanMode,NotebookEdit,Bash"';
const PREVIOUS_CLAUDE_ALLOWED_TOOLS_TEMPLATE_LINE =
  'ALLOWED_TOOLS="Write,Read,Edit,MultiEdit,Glob,Grep,Task,TodoWrite,WebFetch,WebSearch,NotebookEdit,Bash"';
const RALPHRC_DRIVER_COMMENT_LINE =
  "# Platform driver for Ralph loop (claude-code, codex, opencode, copilot, or cursor)";
const PREVIOUS_RALPHRC_DRIVER_COMMENT_LINE =
  "# Platform driver for Ralph loop (claude-code, codex, copilot, or cursor)";
const RALPHRC_IGNORED_DRIVERS_COMMENT_LINE =
  "# Ignored by the codex, opencode, cursor, and copilot drivers.";
const PREVIOUS_RALPHRC_IGNORED_DRIVERS_COMMENT_LINE =
  "# Ignored by the codex, cursor, and copilot drivers.";
const CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK = `# Permission mode for Claude Code CLI (default: bypassPermissions)
# Options: auto, acceptEdits, bypassPermissions, default, dontAsk, plan
CLAUDE_PERMISSION_MODE="bypassPermissions"

`;
const PREVIOUS_CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK = `# Permission mode for Claude Code CLI (default: auto)
# Options: auto, acceptEdits, bypassPermissions, default, dontAsk, plan
CLAUDE_PERMISSION_MODE="auto"

`;
const QUALITY_GATES_TEMPLATE_BLOCK = `# =============================================================================
# QUALITY GATES
# =============================================================================

# Test command to verify TESTS_STATUS claims (e.g. "npm test", "pytest")
# When set, runs after each loop to confirm the agent's test status report.
# Leave empty to trust the agent's TESTS_STATUS without verification.
TEST_COMMAND="\${TEST_COMMAND:-}"

# Semicolon-separated quality gate commands (e.g. "npm run lint;npm run type-check")
# Each command runs after the loop iteration completes.
# Commands must not contain literal semicolons; use wrapper scripts if needed.
QUALITY_GATES="\${QUALITY_GATES:-}"

# Failure mode: warn | block | circuit-breaker
#   warn            - log failures, continue normally (default)
#   block           - suppress exit signal so the loop keeps running
#   circuit-breaker - feed no-progress to circuit breaker
QUALITY_GATE_MODE="\${QUALITY_GATE_MODE:-warn}"

# Timeout in seconds for each gate command
QUALITY_GATE_TIMEOUT="\${QUALITY_GATE_TIMEOUT:-120}"

# Only run gates when the agent signals completion (EXIT_SIGNAL=true)
QUALITY_GATE_ON_COMPLETION_ONLY="\${QUALITY_GATE_ON_COMPLETION_ONLY:-false}"

`;

const LEGACY_RALPHRC_TEMPLATE = `# .ralphrc - Ralph project configuration
# Generated by: ralph enable
# Documentation: https://github.com/frankbria/ralph-claude-code
#
# This file configures Ralph's behavior for this specific project.
# Values here override global Ralph defaults.
# Environment variables override values in this file.

# =============================================================================
# PLATFORM DRIVER
# =============================================================================

# Platform driver for Ralph loop (claude-code, codex, copilot, or cursor)
PLATFORM_DRIVER="\${PLATFORM_DRIVER:-__PLATFORM_DRIVER__}"

# =============================================================================
# PROJECT IDENTIFICATION
# =============================================================================

# Project name (used in prompts and logging)
PROJECT_NAME="\${PROJECT_NAME:-my-project}"

# Project type: javascript, typescript, python, rust, go, unknown
PROJECT_TYPE="\${PROJECT_TYPE:-unknown}"

# =============================================================================
# LOOP SETTINGS
# =============================================================================

# Maximum API calls per hour (rate limiting)
MAX_CALLS_PER_HOUR=100

# Timeout for each Claude Code invocation (in minutes)
CLAUDE_TIMEOUT_MINUTES=15

# Output format: json (structured) or text (legacy)
CLAUDE_OUTPUT_FORMAT="json"

# =============================================================================
# TOOL PERMISSIONS
# =============================================================================

# Comma-separated list of allowed tools for Claude
# Common tools: Write, Read, Edit, Grep, Glob
# Bash patterns: Bash(git *), Bash(npm *), Bash(pytest)
ALLOWED_TOOLS="Write,Read,Edit,Bash(git *),Bash(npm *),Bash(pytest)"

# =============================================================================
# SESSION MANAGEMENT
# =============================================================================

# Enable session continuity (maintain context across loops)
SESSION_CONTINUITY=true

# Session expiration time in hours (start fresh after this time)
SESSION_EXPIRY_HOURS=24

# =============================================================================
# TASK SOURCES
# =============================================================================

# Where to import tasks from (comma-separated)
# Options: local, beads, github
TASK_SOURCES="local"

# GitHub label for task filtering (when github is in TASK_SOURCES)
GITHUB_TASK_LABEL="ralph-task"

# Beads filter for task import (when beads is in TASK_SOURCES)
BEADS_FILTER="status:open"

# =============================================================================
# CIRCUIT BREAKER THRESHOLDS
# =============================================================================

# Open circuit after N loops with no file changes
CB_NO_PROGRESS_THRESHOLD=3

# Open circuit after N loops with the same error
CB_SAME_ERROR_THRESHOLD=5

# Open circuit if output declines by more than N percent
CB_OUTPUT_DECLINE_THRESHOLD=70

# Auto-recovery: cooldown before retry (minutes, 0 = immediate)
CB_COOLDOWN_MINUTES=30

# Auto-reset circuit breaker on startup (bypasses cooldown)
# WARNING: Reduces circuit breaker safety for unattended operation
CB_AUTO_RESET=false

# =============================================================================
# ADVANCED SETTINGS
# =============================================================================

# Minimum Claude CLI version required
CLAUDE_MIN_VERSION="2.0.76"

# Enable verbose logging
RALPH_VERBOSE=false

# Custom prompt file (relative to .ralph/)
# PROMPT_FILE="PROMPT.md"

# Custom fix plan file (relative to .ralph/)
# FIX_PLAN_FILE="@fix_plan.md"

# Custom agent file (relative to .ralph/)
# AGENT_FILE="@AGENT.md"
`;

function renderLegacyRalphrcTemplate(platformId: string): string {
  return LEGACY_RALPHRC_TEMPLATE.replace("__PLATFORM_DRIVER__", platformId);
}

function normalizeManagedRalphrcContent(content: string): string {
  return content
    .replace(PREVIOUS_RALPHRC_DRIVER_COMMENT_LINE, RALPHRC_DRIVER_COMMENT_LINE)
    .replace(PREVIOUS_RALPHRC_IGNORED_DRIVERS_COMMENT_LINE, RALPHRC_IGNORED_DRIVERS_COMMENT_LINE);
}

function renderCurrentRalphrcTemplate(templateContent: string, platformId: string): string {
  return templateContent.replace(
    /PLATFORM_DRIVER="\$\{PLATFORM_DRIVER:-[^"]*\}"/,
    `PLATFORM_DRIVER="\${PLATFORM_DRIVER:-${platformId}}"`
  );
}

export async function renderRalphrcTemplate(platformId: string): Promise<string> {
  const ralphDir = getBundledRalphDir();
  const templateContent = await readFile(join(ralphDir, "templates/ralphrc.template"), "utf-8");
  return renderCurrentRalphrcTemplate(templateContent, platformId);
}

function matchesManagedPermissionVariants(content: string, template: string): boolean {
  if (content === template) {
    return true;
  }

  if (
    content ===
    template
      .replace(CLAUDE_ALLOWED_TOOLS_TEMPLATE_LINE, PREVIOUS_CLAUDE_ALLOWED_TOOLS_TEMPLATE_LINE)
      .replace(CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK, "")
  ) {
    return true;
  }

  if (
    content ===
    template
      .replace(CLAUDE_ALLOWED_TOOLS_TEMPLATE_LINE, PREVIOUS_CLAUDE_ALLOWED_TOOLS_TEMPLATE_LINE)
      .replace(
        CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK,
        PREVIOUS_CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK
      )
  ) {
    return true;
  }

  if (
    content ===
    template.replace(
      CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK,
      PREVIOUS_CLAUDE_PERMISSION_MODE_TEMPLATE_BLOCK
    )
  ) {
    return true;
  }

  return false;
}

async function isRalphrcCustomized(filePath: string, platformId: string): Promise<boolean> {
  const content = normalizeManagedRalphrcContent(await readFile(filePath, "utf-8"));
  const currentTemplate = await renderRalphrcTemplate(platformId);

  if (matchesManagedPermissionVariants(content, currentTemplate)) {
    return false;
  }

  // Check variants without quality gates block (pre-quality-gates installs)
  const templateWithoutQG = currentTemplate.replace(QUALITY_GATES_TEMPLATE_BLOCK, "");
  if (matchesManagedPermissionVariants(content, templateWithoutQG)) {
    return false;
  }

  const legacyTemplate = normalizeManagedRalphrcContent(renderLegacyRalphrcTemplate(platformId));
  return content !== legacyTemplate;
}

export async function isTemplateCustomized(
  filePath: string,
  templateName: string,
  options?: { platformId?: string }
): Promise<boolean> {
  try {
    if (templateName === RALPHRC_TEMPLATE_NAME) {
      return await isRalphrcCustomized(filePath, options?.platformId ?? "claude-code");
    }

    const placeholder = TEMPLATE_PLACEHOLDERS[templateName];
    if (!placeholder) {
      return false;
    }

    const content = await readFile(filePath, "utf-8");
    return !content.includes(placeholder);
  } catch (err) {
    if (isEnoent(err)) {
      return false;
    }

    throw err;
  }
}
